name: PHP Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Pega o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configura o PHP (versão 8.2)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Passo 3: Instala as dependências do projeto usando composer
      - name: Install dependencies with composer
        run: composer install --no-progress --no-suggest --prefer-dist

      # Passo 4: Roda os testes automatizados usando PHPUnit
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml --colors=always
