name: PHP + MySQL CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: vaxlogix_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Verificar versão do PHP
        run: php -v

      - name: Instalar dependências PHP (composer)
        run: |
          if [ -f composer.json ]; then
            composer install
          else
            echo "composer.json não encontrado — pulando instalação PHP"
          fi

      - name: Rodar testes PHP
        run: |
          if [ -d tests ]; then
            ./vendor/bin/phpunit tests
          else
            echo "Nenhuma pasta de testes encontrada — pulando testes PHP"
          fi

      - name: Instalar pacotes front-end (se existir package.json)
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "Nenhum front-end detectado — pulando npm install"
          fi

      - name: Build do front-end (se existir package.json)
        run: |
          if [ -f package.json ]; then
            npm run build
          else
            echo "Nenhum build necessário — pulando npm run build"
          fi
